In [1]:
from multlearn.utils import get_behavior, get_values_spes
import pandas as pd

In [3]:
pars = get_values_spes()

/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-08/V0*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-08/V1*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-08/spe*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-13/V0*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-13/V1*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-13/spe*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-16/V0*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-16/V1*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-16/spe*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-44/V0*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-44/V1*.npy has no corresponding filenames
/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-44/spe*.npy has no corresponding filenames

In [4]:
behavior = get_behavior()

In [5]:
pars.join(behavior)

                                     V0        V1       spe  visualSet  \
subject trialNumber runNumber
1       1           1          0.500000  0.500000  2.197225          0
                    2          0.230159  0.500000  2.302585          1
                    3          0.500000  0.045021  2.397895          2
                    4          0.751575  0.500000  2.484907          3
                    5          0.500000  0.081934  2.564949          4
...                                 ...       ...       ...        ...
64      60          2          0.986405  0.014687  1.961659          1
                    3          0.814752  0.032884  1.871802          2
                    4          0.394574  0.002060  1.887070          3
                    5          0.313147  0.014687  1.902108          4
                    6          0.814752  0.024154  2.273598          5

                               audioPair_1  audioPair_2  audioPair_3  \
subject trialNumber runNumber
1       1           1                    1            0            2
                    2                    1            0            2
                    3                    1            0            2
                    4                    1            0            2
                    5                    1            0            2
...                                    ...          ...          ...
64      60          2                    2            0            1
                    3                    2            0            1
                    4                    2            0            1
                    5                    2            0            1
                    6                    2            0            1

                               tactilePair_1  tactilePair_2  tactilePair_3  \
subject trialNumber runNumber
1       1           1                      0              1              2
                    2                      0              1              2
                    3                      0              1              2
                    4                      0              1              2
                    5                      0              1              2
...                                      ...            ...            ...
64      60          2                      1              2              0
                    3                      1              2              0
                    4                      1              2              0
                    5                      1              2              0
                    6                      1              2              0

                               ...  feedbackOnsetTime  responseTimeThreshold  \
subject trialNumber runNumber  ...
1       1           1          ...           7.222282                      3
                    2          ...           7.222282                      3
                    3          ...           7.222282                      3
                    4          ...           7.222282                      3
                    5          ...           7.222282                      3
...                            ...                ...                    ...
64      60          2          ...         495.626451                      3
                    3          ...         498.333907                      3
                    4          ...         491.541684                      3
                    5          ...         492.309874                      3
                    6          ...         486.628554                      3

                               totalAccuracy  totalErrorRate  accurateIndex  \
subject trialNumber runNumber
1       1           1               0.000000        1.000000              1
                    2               1.000000        0.000000              1
                    3               1.000000        0.000000              1
                    4               0.000000        1.000000              1
                    5               1.000000        0.000000              1
...                                      ...             ...            ...
64      60          2               0.933333        0.066667             56
                    3               0.847458        0.152542             50
                    4               0.750000        0.250000             46
                    5               0.666667        0.333333             40
                    6               0.900000        0.100000             54

                              inaccurateIndex  feedbackAccuracy  \
subject trialNumber runNumber
1       1           1                       1                 1
                    2                       1                 1
                    3                       1                 1
                    4                       1                 1
                    5                       1                 1
...                                       ...               ...
64      60          2                       5                 0
                    3                      10                 1
                    4                      15                 1
                    5                      21                 1
                    6                       7                 0

                               feedbackOffsetTime  action  stimulusPair
subject trialNumber runNumber
1       1           1                    8.222282     0.0        (0, 2)
                    2                    8.222282     0.0        (1, 0)
                    3                    8.222282     1.0        (0, 2)
                    4                    8.222282     0.0        (2, 1)
                    5                    8.222282     0.0        (1, 1)
...                                           ...     ...           ...
64      60          2                  496.626451     0.0        (1, 0)
                    3                  499.333907     0.0        (1, 2)
                    4                  492.541684     1.0        (2, 1)
                    5                  493.309874     0.0        (2, 0)
                    6                  487.628554     1.0        (2, 2)

[20880 rows x 35 columns]

In [5]:
pd.MultiIndex.from_product([range(1, 61), range(1, 7)], names=['trialNumber', 'runNumber']).to_frame()

                       trialNumber  runNumber
trialNumber runNumber
1           1                    1          1
            2                    1          2
            3                    1          3
            4                    1          4
            5                    1          5
...                            ...        ...
60          2                   60          2
            3                   60          3
            4                   60          4
            5                   60          5
            6                   60          6

[360 rows x 2 columns]

In [4]:
!ls /Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-01

BIC_PearceExtra.npy        betas_PearceExtra.tsv
V0_PearceExtra.npy         rpePearceExtra.mat
V1_PearceExtra.npy         spe.mat
alphas2Pos_PearceExtra.tsv spe.npy
alphasPos_PearceExtra.tsv

In [6]:
import numpy as np
np.load('/Volumes/SDrive/multlearn-sns/Modelling/Fitting/bestFittingVals/sub-01/V0_PearceExtra.npy').shape

(6, 61)

In [6]:
pd.read_csv(get_behavior()[0])

,trialNumber,runNumber,visualSet,audioPair_1,audioPair_2,audioPair_3,tactilePair_1,tactilePair_2,tactilePair_3,visual,...,feedbackOnsetTime,responseTimeThreshold,totalAccuracy,totalErrorRate,accurateIndex,inaccurateIndex,feedbackAccuracy,feedbackOffsetTime,action,stimulusPair
0,1,1,0,1,0,2,0,1,2,0,...,7.222282,3,0.000000,1.000000,1,1,1,8.222282,0.0,"(0, 2)"
1,2,1,0,1,0,2,0,1,2,1,...,15.242718,3,0.000000,1.000000,1,2,1,16.242718,1.0,"(1, 1)"
2,3,1,0,1,0,2,0,1,2,2,...,23.062699,3,0.333333,0.666667,1,3,1,24.062699,0.0,"(2, 2)"
3,4,1,0,1,0,2,0,1,2,0,...,31.765834,3,0.250000,0.750000,2,3,1,32.765834,1.0,"(0, 0)"
4,5,1,0,1,0,2,0,1,2,2,...,38.815954,3,0.200000,0.800000,2,4,0,39.815954,0.0,"(2, 1)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,56,6,5,1,0,2,0,1,2,0,...,459.820987,3,0.851852,0.148148,46,9,1,460.820987,1.0,"(0, 2)"
356,57,6,5,1,0,2,0,1,2,2,...,468.005009,3,0.854545,0.145455,47,9,1,469.005009,1.0,"(2, 1)"
357,58,6,5,1,0,2,0,1,2,1,...,475.647851,3,0.857143,0.142857,48,9,1,476.647851,0.0,"(1, 0)"
358,59,6,5,1,0,2,0,1,2,2,...,483.903012,3,0.859649,0.140351,49,9,1,484.903012,0.0,"(2, 2)"
359,60,6,5,1,0,2,0,1,2,0,...,491.389802,3,0.862069,0.137931,50,9,0,492.389802,0.0,"(0, 1)"

In [3]:
!ls /Volumes/SDrive/data/sourcedata/behavior/modified_files/

modified_participant01_savedValues.csv modified_participant34_savedValues.csv
modified_participant02_savedValues.csv modified_participant35_savedValues.csv
modified_participant03_savedValues.csv modified_participant36_savedValues.csv
modified_participant04_savedValues.csv modified_participant37_savedValues.csv
modified_participant05_savedValues.csv modified_participant38_savedValues.csv
modified_participant06_savedValues.csv modified_participant39_savedValues.csv
modified_participant07_savedValues.csv modified_participant40_savedValues.csv
modified_participant08_savedValues.csv modified_participant41_savedValues.csv
modified_participant09_savedValues.csv modified_participant42_savedValues.csv
modified_participant10_savedValues.csv modified_participant43_savedValues.csv
modified_participant11_savedValues.csv modified_participant44_savedValues.csv
modified_participant12_savedValues.csv modified_participant45_savedValues.csv
modified_participant13_savedValues.csv modified_participant46_savedValues.csv
modified_participant14_savedValues.csv modified_participant47_savedValues.csv
modified_participant15_savedValues.csv modified_participant48_savedValues.csv
modified_participant16_savedValues.csv modified_participant49_savedValues.csv
modified_participant17_savedValues.csv modified_participant50_savedValues.csv
modified_participant18_savedValues.csv modified_participant51_savedValues.csv
modified_participant19_savedValues.csv modified_participant52_savedValues.csv
modified_participant20_savedValues.csv modified_participant53_savedValues.csv
modified_participant21_savedValues.csv modified_participant54_savedValues.csv
modified_participant22_savedValues.csv modified_participant55_savedValues.csv
modified_participant23_savedValues.csv modified_participant56_savedValues.csv
modified_participant24_savedValues.csv modified_participant57_savedValues.csv
modified_participant25_savedValues.csv modified_participant58_savedValues.csv
modified_participant26_savedValues.csv modified_participant59_savedValues.csv
modified_participant27_savedValues.csv modified_participant60_savedValues.csv
modified_participant28_savedValues.csv modified_participant61_savedValues.csv
modified_participant29_savedValues.csv modified_participant62_savedValues.csv
modified_participant30_savedValues.csv modified_participant63_savedValues.csv
modified_participant33_savedValues.csv modified_participant64_savedValues.csv

In [1]:
import pandas as pd
import os.path as op

In [5]:
subjects = list(range(1, 65))
subjects.pop(subjects.index(31))
subjects.pop(subjects.index(32))
data_folder = '/Volumes/SDrive/data/'

In [8]:
df = []

for subject in subjects:
    d = pd.read_csv(op.join(data_folder, 'sourcedata', 'behavior', 'modified_files', f'modified_participant{subject:02d}_savedValues.csv'))

    df.append(d.set_index(['runNumber', 'trialNumber']))

df = pd.concat(df, keys=subjects, names=['subject'])

In [9]:
df

                               visualSet  audioPair_1  audioPair_2  \
subject runNumber trialNumber
1       1         1                    0            1            0
                  2                    0            1            0
                  3                    0            1            0
                  4                    0            1            0
                  5                    0            1            0
...                                  ...          ...          ...
64      6         56                   5            2            0
                  57                   5            2            0
                  58                   5            2            0
                  59                   5            2            0
                  60                   5            2            0

                               audioPair_3  tactilePair_1  tactilePair_2  \
subject runNumber trialNumber
1       1         1                      2              0              1
                  2                      2              0              1
                  3                      2              0              1
                  4                      2              0              1
                  5                      2              0              1
...                                    ...            ...            ...
64      6         56                     1              1              2
                  57                     1              1              2
                  58                     1              1              2
                  59                     1              1              2
                  60                     1              1              2

                               tactilePair_3  visual  audio  tactile  ...  \
subject runNumber trialNumber                                         ...
1       1         1                        2       0    NaN      2.0  ...
                  2                        2       1    NaN      1.0  ...
                  3                        2       2    NaN      2.0  ...
                  4                        2       0    NaN      0.0  ...
                  5                        2       2    NaN      1.0  ...
...                                      ...     ...    ...      ...  ...
64      6         56                       0       0    1.0      NaN  ...
                  57                       0       1    0.0      NaN  ...
                  58                       0       2    2.0      NaN  ...
                  59                       0       1    1.0      NaN  ...
                  60                       0       2    2.0      NaN  ...

                               feedbackOnsetTime  responseTimeThreshold  \
subject runNumber trialNumber
1       1         1                     7.222282                      3
                  2                    15.242718                      3
                  3                    23.062699                      3
                  4                    31.765834                      3
                  5                    38.815954                      3
...                                          ...                    ...
64      6         56                  455.647441                      3
                  57                  462.374612                      3
                  58                  470.083529                      3
                  59                  478.343370                      3
                  60                  486.628554                      3

                              totalAccuracy  totalErrorRate  accurateIndex  \
subject runNumber trialNumber
1       1         1                0.000000        1.000000              1
                  2                0.000000        1.000000              1
                  3                0.333333        0.666667              1
                  4                0.250000        0.750000              2
                  5                0.200000        0.800000              2
...                                     ...             ...            ...
64      6         56               0.892857        0.107143             50
                  57               0.894737        0.105263             51
                  58               0.896552        0.103448             52
                  59               0.898305        0.101695             53
                  60               0.900000        0.100000             54

                               inaccurateIndex  feedbackAccuracy  \
subject runNumber trialNumber
1       1         1                          1                 1
                  2                          2                 1
                  3                          3                 1
                  4                          3                 1
                  5                          4                 0
...                                        ...               ...
64      6         56                         7                 1
                  57                         7                 1
                  58                         7                 0
                  59                         7                 1
                  60                         7                 0

                               feedbackOffsetTime  action  stimulusPair
subject runNumber trialNumber
1       1         1                      8.222282     0.0        (0, 2)
                  2                     16.242718     1.0        (1, 1)
                  3                     24.062699     0.0        (2, 2)
                  4                     32.765834     1.0        (0, 0)
                  5                     39.815954     0.0        (2, 1)
...                                           ...     ...           ...
64      6         56                   456.647441     1.0        (0, 1)
                  57                   463.374612     0.0        (1, 0)
                  58                   471.083529     1.0        (2, 2)
                  59                   479.343370     1.0        (1, 1)
                  60                   487.628554     1.0        (2, 2)

[22080 rows x 32 columns]

## Read in SPE

In [16]:
from scipy.io import loadmat
import numpy as np

In [36]:
spes = []

for subject in subjects:
    print(subject)

    try:
        spe = loadmat(f'/Volumes/SDrive/data/fittedParameters/sub-{subject:02d}/spe.mat')['spe']

        spe = pd.DataFrame(spe, columns=pd.Index(np.arange(1, 61), name='trialNumber'), index=pd.Index(np.arange(1, 7), name='runNumber'))

        spe = spe.stack().to_frame('spe')

        spes.append(spe)

    except Exception as e:
        subjects.pop(subjects.index(subject))
        print(f'There was a problem with subject {subject}:\n{e}')

spes = pd.concat(spes, keys=subjects, names=['subject'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
17
18
19
20
21
22
23
24
25
26
27
28
29
30
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64

In [39]:
df = df.join(spes)

In [40]:
import seaborn as sns

In [41]:
df

                               visualSet  audioPair_1  audioPair_2  \
subject runNumber trialNumber
1       1         1                    0            1            0
                  2                    0            1            0
                  3                    0            1            0
                  4                    0            1            0
                  5                    0            1            0
...                                  ...          ...          ...
64      6         56                   5            2            0
                  57                   5            2            0
                  58                   5            2            0
                  59                   5            2            0
                  60                   5            2            0

                               audioPair_3  tactilePair_1  tactilePair_2  \
subject runNumber trialNumber
1       1         1                      2              0              1
                  2                      2              0              1
                  3                      2              0              1
                  4                      2              0              1
                  5                      2              0              1
...                                    ...            ...            ...
64      6         56                     1              1              2
                  57                     1              1              2
                  58                     1              1              2
                  59                     1              1              2
                  60                     1              1              2

                               tactilePair_3  visual  audio  tactile  ...  \
subject runNumber trialNumber                                         ...
1       1         1                        2       0    NaN      2.0  ...
                  2                        2       1    NaN      1.0  ...
                  3                        2       2    NaN      2.0  ...
                  4                        2       0    NaN      0.0  ...
                  5                        2       2    NaN      1.0  ...
...                                      ...     ...    ...      ...  ...
64      6         56                       0       0    1.0      NaN  ...
                  57                       0       1    0.0      NaN  ...
                  58                       0       2    2.0      NaN  ...
                  59                       0       1    1.0      NaN  ...
                  60                       0       2    2.0      NaN  ...

                               responseTimeThreshold  totalAccuracy  \
subject runNumber trialNumber
1       1         1                                3       0.000000
                  2                                3       0.000000
                  3                                3       0.333333
                  4                                3       0.250000
                  5                                3       0.200000
...                                              ...            ...
64      6         56                               3       0.892857
                  57                               3       0.894737
                  58                               3       0.896552
                  59                               3       0.898305
                  60                               3       0.900000

                              totalErrorRate  accurateIndex  inaccurateIndex  \
subject runNumber trialNumber
1       1         1                 1.000000              1                1
                  2                 1.000000              1                2
                  3                 0.666667              1                3
                  4                 0.750000              2                3
                  5                 0.800000              2                4
...                                      ...            ...              ...
64      6         56                0.107143             50                7
                  57                0.105263             51                7
                  58                0.103448             52                7
                  59                0.101695             53                7
                  60                0.100000             54                7

                               feedbackAccuracy  feedbackOffsetTime  action  \
subject runNumber trialNumber
1       1         1                           1            8.222282     0.0
                  2                           1           16.242718     1.0
                  3                           1           24.062699     0.0
                  4                           1           32.765834     1.0
                  5                           0           39.815954     0.0
...                                         ...                 ...     ...
64      6         56                          1          456.647441     1.0
                  57                          1          463.374612     0.0
                  58                          0          471.083529     1.0
                  59                          1          479.343370     1.0
                  60                          0          487.628554     1.0

                               stimulusPair       spe
subject runNumber trialNumber
1       1         1                  (0, 2)  2.197225
                  2                  (1, 1)  2.302585
                  3                  (2, 2)  2.397895
                  4                  (0, 0)  2.484907
                  5                  (2, 1)  2.564949
...                                     ...       ...
64      6         56                 (0, 1)  3.060271
                  57                 (1, 0)  1.871802
                  58                 (2, 2)  2.397895
                  59                 (1, 1)  2.258782
                  60                 (2, 2)  2.273598

[22080 rows x 33 columns]