In [4]:
import pandas as pd
import os.path as op

In [5]:
subjects = list(range(1, 65))
subjects.pop(subjects.index(31))
subjects.pop(subjects.index(32))
data_folder = '/Volumes/SDrive/data/'

In [8]:
df = []

for subject in subjects:
    d = pd.read_csv(op.join(data_folder, 'sourcedata', 'behavior', 'modified_files', f'modified_participant{subject:02d}_savedValues.csv'))

    df.append(d.set_index(['runNumber', 'trialNumber']))

df = pd.concat(df, keys=subjects, names=['subject'])

In [9]:
df

                               visualSet  audioPair_1  audioPair_2  \
subject runNumber trialNumber
1       1         1                    0            1            0
                  2                    0            1            0
                  3                    0            1            0
                  4                    0            1            0
                  5                    0            1            0
...                                  ...          ...          ...
64      6         56                   5            2            0
                  57                   5            2            0
                  58                   5            2            0
                  59                   5            2            0
                  60                   5            2            0

                               audioPair_3  tactilePair_1  tactilePair_2  \
subject runNumber trialNumber
1       1         1                      2              0              1
                  2                      2              0              1
                  3                      2              0              1
                  4                      2              0              1
                  5                      2              0              1
...                                    ...            ...            ...
64      6         56                     1              1              2
                  57                     1              1              2
                  58                     1              1              2
                  59                     1              1              2
                  60                     1              1              2

                               tactilePair_3  visual  audio  tactile  ...  \
subject runNumber trialNumber                                         ...
1       1         1                        2       0    NaN      2.0  ...
                  2                        2       1    NaN      1.0  ...
                  3                        2       2    NaN      2.0  ...
                  4                        2       0    NaN      0.0  ...
                  5                        2       2    NaN      1.0  ...
...                                      ...     ...    ...      ...  ...
64      6         56                       0       0    1.0      NaN  ...
                  57                       0       1    0.0      NaN  ...
                  58                       0       2    2.0      NaN  ...
                  59                       0       1    1.0      NaN  ...
                  60                       0       2    2.0      NaN  ...

                               feedbackOnsetTime  responseTimeThreshold  \
subject runNumber trialNumber
1       1         1                     7.222282                      3
                  2                    15.242718                      3
                  3                    23.062699                      3
                  4                    31.765834                      3
                  5                    38.815954                      3
...                                          ...                    ...
64      6         56                  455.647441                      3
                  57                  462.374612                      3
                  58                  470.083529                      3
                  59                  478.343370                      3
                  60                  486.628554                      3

                              totalAccuracy  totalErrorRate  accurateIndex  \
subject runNumber trialNumber
1       1         1                0.000000        1.000000              1
                  2                0.000000        1.000000              1
                  3                0.333333        0.666667              1
                  4                0.250000        0.750000              2
                  5                0.200000        0.800000              2
...                                     ...             ...            ...
64      6         56               0.892857        0.107143             50
                  57               0.894737        0.105263             51
                  58               0.896552        0.103448             52
                  59               0.898305        0.101695             53
                  60               0.900000        0.100000             54

                               inaccurateIndex  feedbackAccuracy  \
subject runNumber trialNumber
1       1         1                          1                 1
                  2                          2                 1
                  3                          3                 1
                  4                          3                 1
                  5                          4                 0
...                                        ...               ...
64      6         56                         7                 1
                  57                         7                 1
                  58                         7                 0
                  59                         7                 1
                  60                         7                 0

                               feedbackOffsetTime  action  stimulusPair
subject runNumber trialNumber
1       1         1                      8.222282     0.0        (0, 2)
                  2                     16.242718     1.0        (1, 1)
                  3                     24.062699     0.0        (2, 2)
                  4                     32.765834     1.0        (0, 0)
                  5                     39.815954     0.0        (2, 1)
...                                           ...     ...           ...
64      6         56                   456.647441     1.0        (0, 1)
                  57                   463.374612     0.0        (1, 0)
                  58                   471.083529     1.0        (2, 2)
                  59                   479.343370     1.0        (1, 1)
                  60                   487.628554     1.0        (2, 2)

[22080 rows x 32 columns]

## Read in SPE

In [16]:
from scipy.io import loadmat
import numpy as np

In [36]:
spes = []

for subject in subjects:
    print(subject)

    try:
        spe = loadmat(f'/Volumes/SDrive/data/fittedParameters/sub-{subject:02d}/spe.mat')['spe']

        spe = pd.DataFrame(spe, columns=pd.Index(np.arange(1, 61), name='trialNumber'), index=pd.Index(np.arange(1, 7), name='runNumber'))

        spe = spe.stack().to_frame('spe')

        spes.append(spe)

    except Exception as e:
        subjects.pop(subjects.index(subject))
        print(f'There was a problem with subject {subject}:\n{e}')

spes = pd.concat(spes, keys=subjects, names=['subject'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
17
18
19
20
21
22
23
24
25
26
27
28
29
30
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64

In [39]:
df = df.join(spes)

In [40]:
import seaborn as sns

In [41]:
df

                               visualSet  audioPair_1  audioPair_2  \
subject runNumber trialNumber
1       1         1                    0            1            0
                  2                    0            1            0
                  3                    0            1            0
                  4                    0            1            0
                  5                    0            1            0
...                                  ...          ...          ...
64      6         56                   5            2            0
                  57                   5            2            0
                  58                   5            2            0
                  59                   5            2            0
                  60                   5            2            0

                               audioPair_3  tactilePair_1  tactilePair_2  \
subject runNumber trialNumber
1       1         1                      2              0              1
                  2                      2              0              1
                  3                      2              0              1
                  4                      2              0              1
                  5                      2              0              1
...                                    ...            ...            ...
64      6         56                     1              1              2
                  57                     1              1              2
                  58                     1              1              2
                  59                     1              1              2
                  60                     1              1              2

                               tactilePair_3  visual  audio  tactile  ...  \
subject runNumber trialNumber                                         ...
1       1         1                        2       0    NaN      2.0  ...
                  2                        2       1    NaN      1.0  ...
                  3                        2       2    NaN      2.0  ...
                  4                        2       0    NaN      0.0  ...
                  5                        2       2    NaN      1.0  ...
...                                      ...     ...    ...      ...  ...
64      6         56                       0       0    1.0      NaN  ...
                  57                       0       1    0.0      NaN  ...
                  58                       0       2    2.0      NaN  ...
                  59                       0       1    1.0      NaN  ...
                  60                       0       2    2.0      NaN  ...

                               responseTimeThreshold  totalAccuracy  \
subject runNumber trialNumber
1       1         1                                3       0.000000
                  2                                3       0.000000
                  3                                3       0.333333
                  4                                3       0.250000
                  5                                3       0.200000
...                                              ...            ...
64      6         56                               3       0.892857
                  57                               3       0.894737
                  58                               3       0.896552
                  59                               3       0.898305
                  60                               3       0.900000

                              totalErrorRate  accurateIndex  inaccurateIndex  \
subject runNumber trialNumber
1       1         1                 1.000000              1                1
                  2                 1.000000              1                2
                  3                 0.666667              1                3
                  4                 0.750000              2                3
                  5                 0.800000              2                4
...                                      ...            ...              ...
64      6         56                0.107143             50                7
                  57                0.105263             51                7
                  58                0.103448             52                7
                  59                0.101695             53                7
                  60                0.100000             54                7

                               feedbackAccuracy  feedbackOffsetTime  action  \
subject runNumber trialNumber
1       1         1                           1            8.222282     0.0
                  2                           1           16.242718     1.0
                  3                           1           24.062699     0.0
                  4                           1           32.765834     1.0
                  5                           0           39.815954     0.0
...                                         ...                 ...     ...
64      6         56                          1          456.647441     1.0
                  57                          1          463.374612     0.0
                  58                          0          471.083529     1.0
                  59                          1          479.343370     1.0
                  60                          0          487.628554     1.0

                               stimulusPair       spe
subject runNumber trialNumber
1       1         1                  (0, 2)  2.197225
                  2                  (1, 1)  2.302585
                  3                  (2, 2)  2.397895
                  4                  (0, 0)  2.484907
                  5                  (2, 1)  2.564949
...                                     ...       ...
64      6         56                 (0, 1)  3.060271
                  57                 (1, 0)  1.871802
                  58                 (2, 2)  2.397895
                  59                 (1, 1)  2.258782
                  60                 (2, 2)  2.273598

[22080 rows x 33 columns]